<?php

namespace app\modules\tournament;

use Yii;
use yii\base\Module;
use yii\helpers\VarDumper;

/***
 *
 */
class tournament extends Module
{

    public $controllerNamespace = "app\modules\\tournament\controllers";


    public function init()
    {


        $this->layoutPath = Yii::$app->basePath . "/views/layouts";
        $this->layout = "index";
        parent::init(); // TODO: Change the autogenerated stub
    }

}