<?php

namespace app\modules\tournament\assets;

use yii\web\AssetBundle;
use yii\web\View;

class TournamentAssets extends AssetBundle
{

    public $sourcePath = "@app/modules/tournament/assets";

    public $js = [];

    public function init()
    {
        $this->jsOptions["position"] = View::POS_END;
        parent::init(); // TODO: Change the autogenerated stub
    }



}